import type { GetServerSideProps, NextPage } from 'next';
import Head from 'next/head';
import React from 'react';
import HomePage from 'components/home-page';
import { getLayoutData } from 'fetcher/fetcher';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomePage />
    </div>
  );
};

export const getServerSideProps: GetServerSideProps = async () => {
  const layout = await getLayoutData();
  return { props: { layout } };
};

export default Home;
